<?php
return [
    'paginate'          => '25',
    'date_search'       => 'Y-m-d',
    'date_show'         => 'd/m/Y',
    'datetime'          => 'd/m/Y H:i',
    'datetime_db'       => 'Y/m/d H:i',
    'datetime_ts'       => 'm/d/Y H:i',
    'yes'               => '1',
    'no'                => '0',
    'percents'          => '100',
    'hour'              => 60,
    'decimal'           => 2,
    'sunday'            => 0,
    'saturday'          => 6,
    'overtime'          => [
        'registered'    => '1',
        'admin_approve' => '2',
        'approved'      => '3',
        'confirm'       => '4',
        'admin_confirm' => '5',
        'confirmed'     => '6',
        'rejected'      => '7',
        'cancel'        => '8',
    ],
    'timesheet'         => [
        'normal'        => '1',
        'reconfirm'     => '2',
    ],
    'time'              => 'H:i',
    'date_img'          => 'Y/m/d',
    'remotes'           => [
        'pending'       => '1',
        'approved'      => '2',
        'rejected'      => '3',
        'cancelled' => '4',
    ],
    'leaves' => [
        'pending' => '1',
        'confirming' => '2',
        'approved' => '3',
        'rejected' => '4',
        'cancelled' => '5',
    ],
    'position' => [
        'staff' => '1',
        'po' => '2',
        'lead' => '3',
        'culi' => '4',
    ],
    'gender' => [
        'male' => '1',
        'female' => '2',
    ],
    'contract' => [
        'probationary' => '1',
        'staff' => '2',
        'intern' => '3',
    ],
    'status_user' => [
        'active' => '1',
        'inactive' => '2',
    ],
    'role' => [
        'admin' => '1',
        'member' => '2',
        'accounter' => '3',
        'hr' => '4',
        'po' => '5',
    ],
    'leave_hours' => [
        'leave_hours_month' => '480',
        'leave_hours_half_month' => '240',
        'leave_days' => '1',
        'leave_days_month' => '15'
    ],
    'type' => [
        'paid_leave' => '1',
        'sister_leave' => '2',
        'unpaid_leave' => '3',
        'leave_mode' => '4',
        'Insurance_leave' => '5'
    ],
    'add_minutes' => '10',
    'random' => '10',
    'import_data'        => [
        'code'           => 0,
        'record_date'    => 2,
        'in_time'        => 3,
        'out_time'       => 4,
        'status'         => 5,
        'overtime_hours' => 7,
        'time'           => 8,
    ],
    'home'               => [
        'userId'         => 'MaID',
        'recordDate'     => 'Ngay',
        'inTime'         => 'GioDen',
        'outTime'        => 'GioVe',
    ],
    'in_out'             => [
        'register'       => '1',
        'approve'        => '2',
        'reject'         => '3',
        'cancel'         => '4',
    ],
];
